server:
  port: 9999
  connection-timeout: 1800000

spring:
  devtools:
    livereload:
      enabled: true
  servlet:
    multipart:
      maxFileSize: 300MB
      maxRequestSize: 300MB
  mvc:
    hidden-method:
      filter:
        enabled: true
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://211.172.247.228:1433;databaseName=mv;encrypt=false
    username: sa
    password: db@!!.!&@.@$&.@@*svr
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none # none # create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      javax:
        persistence:
          query:
            timeout: 1800000
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
      dialect: org.hibernate.dialect.SQLServer2012Dialect

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
